### ISSUE TITLE
Add support of plain program output (without colors and text styles)

### ISSUE THREAD

**Issue by OStrekalovsky** [smilart/nvidia-cdl#3]
It's can be usefull to parse output from that program by another program. 
Color and style symbols prevent simple and reliable parsing.
Please, add argument for turn off output decoration.

**Comment by AlexanderKomarov** [comment]
@OStrekalovsky it's a great idea! If you want you can add this argument independently

**Comment by OStrekalovsky** [comment]
I think, that my C++ skills are not well enough for that.

**Comment by AlexanderKomarov** [comment]
@OStrekalovsky Done!
